[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["day-01", "day-02", "day-03", "day-04", "day-05", "day-06", "day-07", "day-08", "day-09", "day-10"]
[dependencies]

